#loader.py - reads metric csvs produced by the r pipeline into pandas dataframes
#used by the api layer and any downstream python modeling code

import pandas as pd
from pathlib import Path

OUTPUTS_DIR = Path(__file__).resolve().parents[2] / "data" / "outputs"


def load_metric(filename: str) -> pd.DataFrame:
    #resolves full path and raises if the file hasn't been generated by the r pipeline yet
    path = OUTPUTS_DIR / filename
    if not path.exists():
        raise FileNotFoundError(f"Metric file not found: {path}")
    return pd.read_csv(path)


def load_all_metrics() -> dict[str, pd.DataFrame]:
    #maps short metric keys to their output filenames for bulk loading
    files = {
        "epa":             "epa_by_team.csv",
        "success_rate":    "success_rate_by_team.csv",
        "wpa":             "wpa_by_team.csv",
        "redzone":         "redzone_efficiency.csv",
        "drive_efficiency":"drive_efficiency.csv",
    }
    return {name: load_metric(fname) for name, fname in files.items()}
